[package]
name = "evmr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.10"
bit-set = "0.5"
bytes = "1.1"
sha3 = { version = "0.9", default-features = false }
num_enum = "0.5"