[workspace]
resolver = "2"
members = ["bins/*", "crates/*"]
default-members = ["crates/revm"]

[profile.release]
lto = true
codegen-units = 1
debug = true

[profile.ethtests]
inherits = "test"
opt-level = 3
