[package]
name = "revm"
version = "0.2.0"
edition = "2018"
license = "Apache-2.0"
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "REVM - Rust Ethereum virtual machine"
repository = "https://github.com/bluealloy/revm"
keywords = ["no_std", "ethereum", "evm"]


[dependencies]
primitive-types = {version ="0.10", features = ["rlp"]}
bytes = "1.1"
sha3 = { version = "0.9", default-features = false}
rlp = { version = "0.5", default-features = false } #used for create2 address calculation
num_enum = "0.5" #used for opcodes from u8 cast
#libs below are for precompiles. See to move them to saparate lib.
num = { version = "0.4.0", default-features = false, features = ["alloc"] }
sha2 = { version = "0.9.3", default-features = false }
borsh = { version = "0.9", default-features = false }
ripemd160 = { version = "0.9.1", default-features = false }
parity-crypto = { version = "0.9.0", default-features = false, features = [ "publickey" ] }
bn = { package="substrate-bn", version="0.6", default-features = false }


[dev-dependencies]
hex = "0.4"