[package]
name = "revm-ethereum-tests"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
revm = {path="../../"}
primitive-types = {version ="0.10", features = ["rlp","serde"]}
bytes = "1.1"
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
walkdir = "2.3"
tokio = { version = "1.12", features = ["full"] }
indicatif = "0.16"