[package]
edition = "2018"
name = "revm-ethereum-tests"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
hash-db = "0.15"
hex = "0.4"
indicatif = "0.16"
plain_hasher = "0.2"
primitive-types = {version = "0.10", features = ["rlp", "serde"]}

revm = {path="../../crates/revm"}
rlp = {version = "0.5", default-features = false}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha3 = {version = "0.9", default-features = false}
thiserror = "1.0"
triehash = "0.8"
walkdir = "2.3"
