on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]

name: Ethereum Tests

jobs:
  tests-stable:
    name: Ethereum Tests (Stable)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Checkout ethereum/tests
        uses: actions/checkout@v3
        with:
          repository: ethereum/tests
          path: ethtests
          submodules: recursive

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run Ethereum tests
        run: |
          cargo run --profile ethtests -p revme -- \
          statetest \
          ethtests/GeneralStateTests/ \
          ethtests/LegacyTests/Constantinople/GeneralStateTests/ \
          tests/EIPTests/StateTests/stEIP5656-MCOPY/ \
          tests/EIPTests/StateTests/stEIP1153-transientStorage/
